version: '3.7'
services:
  npm:
    image: '${IMAGE_CONTAINER_PREFIX}_npm'
    container_name: '${IMAGE_CONTAINER_PREFIX}_npm'
    build:
      context: './npm'
    volumes:
      - ./src:/src
    ports:
      - 8080:8080
    working_dir: /src
    entrypoint: ['npm']
  vue:
    image: '${IMAGE_CONTAINER_PREFIX}_vue_cli'
    container_name: '${IMAGE_CONTAINER_PREFIX}_vue_cli'
    build:
      context: './npm'
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    working_dir: /src
    entrypoint: ['vue']