version: '3.7'
services:
  npm:
    build:
      context: './npm'
    container_name: '${PROJECT_NAME}_npm'
    volumes:
      - ./src:/src
    ports:
      - 5000:5000
    working_dir: /src
    restart: unless-stopped
    command: 
      "npm run dev"
  vue:
    ports:
      - 8000:8000
    build:
      context: './npm'
    container_name: '${PROJECT_NAME}_vue_cli'
    volumes:
      - ./src:/src
    working_dir: /src
    entrypoint: ['vue']
  nginx:
    restart: unless-stopped
    container_name: '${PROJECT_NAME}_nginx'
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - npm
